import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import "hardhat-deploy";
import "@ericxstone/hardhat-blockscout-verify";


const config: HardhatUserConfig = {
    defaultNetwork: "mynw",
    solidity: {
      compilers: [
        { version: "0.8.19", settings: {} },
        { version: "0.8.18", settings: {} },
        { version: "0.8.17", settings: {} },
        { version: "0.8.16", settings: {} },
        { version: "0.8.15", settings: {} },
        { version: "0.8.14", settings: {} },
        { version: "0.8.13", settings: {} },
        { version: "0.8.12", settings: {} },
        { version: "0.8.11", settings: {} },
        { version: "0.8.10", settings: {} },
        { version: "0.8.9", settings: {} },
        { version: "0.8.8", settings: {} },
        { version: "0.8.7", settings: {} },
        { version: "0.8.6", settings: {} },
        { version: "0.8.5", settings: {} },
        { version: "0.8.4", settings: {} },
        { version: "0.8.3", settings: {} },
        { version: "0.8.2", settings: {} },
        { version: "0.8.1", settings: {} },
        { version: "0.8.0", settings: {} },
        { version: "0.7.6", settings: {} },
        { version: "0.7.5", settings: {} },
        { version: "0.7.4", settings: {} },
        { version: "0.7.3", settings: {} },
        { version: "0.7.2", settings: {} },
        { version: "0.7.1", settings: {} },
        { version: "0.7.0", settings: {} },
        { version: "0.6.12", settings: {} },
        { version: "0.6.11", settings: {} },
        { version: "0.6.10", settings: {} },
        { version: "0.6.9", settings: {} },
        { version: "0.6.8", settings: {} },
        { version: "0.6.7", settings: {} },
        { version: "0.6.6", settings: {} },
        { version: "0.6.5", settings: {} },
        { version: "0.6.4", settings: {} },
        { version: "0.6.3", settings: {} },
        { version: "0.6.2", settings: {} },
        { version: "0.6.1", settings: {} },
        { version: "0.6.0", settings: {} },
        { version: "0.5.17", settings: {} },
        { version: "0.5.16", settings: {} },
        { version: "0.5.15", settings: {} },
        { version: "0.5.14", settings: {} },
        { version: "0.5.13", settings: {} },
        { version: "0.5.12", settings: {} },
        { version: "0.5.11", settings: {} },
        { version: "0.5.10", settings: {} },
        { version: "0.5.9", settings: {} },
        { version: "0.5.8", settings: {} },
        { version: "0.5.7", settings: {} },
        { version: "0.5.6", settings: {} },
        { version: "0.5.5", settings: {} },
        { version: "0.5.4", settings: {} },
        { version: "0.5.3", settings: {} },
        { version: "0.5.2", settings: {} },
        { version: "0.5.1", settings: {} },
        { version: "0.5.0", settings: {} },
        { version: "0.4.26", settings: {} },
        { version: "0.4.25", settings: {} },
        { version: "0.4.24", settings: {} },
        { version: "0.4.23", settings: {} },
        { version: "0.4.22", settings: {} },
        { version: "0.4.21", settings: {} },
        { version: "0.4.20", settings: {} },
        { version: "0.4.19", settings: {} },
        { version: "0.4.18", settings: {} },
        { version: "0.4.17", settings: {} },
        { version: "0.4.16", settings: {} },
        { version: "0.4.15", settings: {} },
        { version: "0.4.14", settings: {} },
        { version: "0.4.13", settings: {} },
        { version: "0.4.12", settings: {} },
        { version: "0.4.11", settings: {} },
        { version: "0.4.10", settings: {} },
        { version: "0.4.9", settings: {} },
        { version: "0.4.8", settings: {} },
        { version: "0.4.7", settings: {} },
        { version: "0.4.6", settings: {} },
        { version: "0.4.5", settings: {} },
        { version: "0.4.4", settings: {} },
        { version: "0.4.3", settings: {} },
        { version: "0.4.2", settings: {} },
        { version: "0.4.1", settings: {} },
        { version: "0.4.0", settings: {} },
        { version: "0.3.6", settings: {} },
        { version: "0.3.5", settings: {} },
        { version: "0.3.4", settings: {} },
        { version: "0.3.3", settings: {} },
        { version: "0.3.2", settings: {} },
        { version: "0.3.1", settings: {} },
        { version: "0.3.0", settings: {} },
        { version: "0.2.2", settings: {} },
        { version: "0.2.1", settings: {} },
        { version: "0.2.0", settings: {} },
        { version: "0.1.7", settings: {} },
        { version: "0.1.6", settings: {} },
        { version: "0.1.5", settings: {} },
        { version: "0.1.4", settings: {} },
        { version: "0.1.3", settings: {} },
        { version: "0.1.2", settings: {} },
        { version: "0.1.1", settings: {} },
      ]
    },
    networks: {
      mynw: {
        url: "http://127.0.0.1:8545",
        accounts: {
          mnemonic: "",
        },
        // issue: https://github.com/NomicFoundation/hardhat/issues/3136
        // workaround: https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1167409582
        timeout: 100_000,
      },
    },
  };
  
  export default config;