version: "3.8"
services:
  api_service:
    restart: always
    container_name: api_service
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8003:8003"
    entrypoint:
      - tail
    command:
      - -f
      - /dev/null
    working_dir: /app
    env_file:
      - .env.docker
