basePath: /dapp-moderator/v1
definitions:
  response.JsonResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/response.RespondErr'
      status:
        type: boolean
    type: object
  response.RedisResponse:
    properties:
      value:
        type: string
    type: object
  response.RespondErr:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server Autonomous devices management server.
  title: Generative.xyz APIs
  version: 1.0.0
paths:
  /admin/redis:
    get:
      consumes:
      - application/json
      description: Get Redis
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.RedisResponse'
                  type: array
              type: object
      summary: Get Redis
      tags:
      - Admin
  /quicknode/address/{walletAddress}/balance:
    get:
      consumes:
      - application/json
      description: getaddress balance
      parameters:
      - description: BTC walletAddress
        in: path
        name: walletAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.RedisResponse'
                  type: array
              type: object
      summary: qn_addressBalance RPC Method
      tags:
      - QuickNode
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
