basePath: /dapp-moderator/v1
definitions:
  response.JsonResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/response.RespondErr'
      status:
        type: boolean
    type: object
  response.RedisResponse:
    properties:
      value:
        type: string
    type: object
  response.RespondErr:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server TC-DAPP server.
  title: tcDAPP APIs
  version: 1.0.0
paths:
  /nft-explorer/collections:
    get:
      consumes:
      - application/json
      description: Get Collections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: Get Collections
      tags:
      - nft-explorer
  /nft-explorer/collections/{collectionAddress}:
    get:
      consumes:
      - application/json
      description: Get Collections
      parameters:
      - description: collectionAddress
        in: path
        name: collectionAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: Get Collections
      tags:
      - nft-explorer
  /nft-explorer/collections/{collectionAddress}/nfts:
    get:
      consumes:
      - application/json
      description: Get nfts of a Collectionc
      parameters:
      - description: collectionAddress
        in: path
        name: collectionAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: Get nfts of a Collectionc
      tags:
      - nft-explorer
  /nft-explorer/collections/{collectionAddress}/nfts/{tokenID}:
    get:
      consumes:
      - application/json
      description: Get nft detail of a Collection
      parameters:
      - description: collectionAddress
        in: path
        name: collectionAddress
        required: true
        type: string
      - description: tokenID
        in: path
        name: tokenID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: Get nft detail of a Collection
      tags:
      - nft-explorer
  /nft-explorer/collections/{collectionAddress}/nfts/{tokenID}/content:
    get:
      consumes:
      - application/json
      description: Get nft content of a Collection
      parameters:
      - description: collectionAddress
        in: path
        name: collectionAddress
        required: true
        type: string
      - description: tokenID
        in: path
        name: tokenID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: Get nft content of a Collection
      tags:
      - nft-explorer
  /nft-explorer/nfts:
    get:
      consumes:
      - application/json
      description: Get Nfts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: Get Nfts
      tags:
      - nft-explorer
  /nft-explorer/owner-address/{ownerAddress}/nfts:
    get:
      consumes:
      - application/json
      description: Get nfts of a wallet address
      parameters:
      - description: ownerAddress
        in: path
        name: ownerAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: Get nfts of a wallet address
      tags:
      - nft-explorer
  /quicknode/address/{walletAddress}/balance:
    get:
      consumes:
      - application/json
      description: getaddress balance
      parameters:
      - description: BTC walletAddress
        in: path
        name: walletAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.RedisResponse'
                  type: array
              type: object
      summary: qn_addressBalance RPC Method
      tags:
      - QuickNode
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
